name: boxino
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI / Core
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

  # State Management
  flutter_riverpod: ^2.4.9
  
  # Backend
  supabase_flutter: ^2.4.0
  uuid: ^4.3.3
  
  # Auth
  google_sign_in: ^6.2.1
  
  # Routing
  go_router: ^13.1.0
  http: ^1.2.0

  intl: any

  url_launcher: ^6.2.5
  
  # Push Notifications
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_version: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
